
export enum Token {
    NONE = -1,
    _FINISHED = 0,
    ADD = 1, 
    SUB = 2,
    MUL = 3,
    DIV = 4,
    MOD = 5,
    XOR = 6,
    BITWISEAND = 7,
    BITWISEOR = 8,
    OR = 9,
    AND = 10,
    NOT = 11,
    GT = 12,
    GE = 13,
    LT = 14,
    LE = 15,
    NE = 16,
    EQU = 17, 
    DOT =18,
    COMMA =19,
    COLON = 20,
    SEMICOLON = 21,
    AT = 22,
    DOLLAR = 23,
    LPARENTHESE = 24,
    RPARENTHESE = 25,
    LBRACE = 26,
    RBRACE = 27, 
    NUM = 28,
    VAR = 29,
    HEX = 30,
    REM = 31,
    STRING = 32,
    ADDEQU = 33,
    SUBEQU = 34,
    LBRACKET = 35,
    RBRACKET = 36,
    SHARP = 37,
    CODE = 38,
    DOLLARVAR = 39,
}

// QM_GT = 18, QM_GE, QM_LT, QM_LE, QM_EQU, QM_LIKE, QM_BETWEEN,
// LBBRACE, RBBRACE,